// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShippeeAPI.Context;

#nullable disable

namespace ShippeeAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShippeeAPI.Annoucement_Company", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<int?>("id_job")
                        .HasColumnType("int");

                    b.Property<int?>("id_naf_division")
                        .HasColumnType("int");

                    b.Property<int?>("id_recruiter")
                        .HasColumnType("int");

                    b.Property<DateTime?>("publish_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("title")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("id_job");

                    b.HasIndex("id_naf_division");

                    b.HasIndex("id_recruiter");

                    b.ToTable("Annoucement_Companies");
                });

            modelBuilder.Entity("ShippeeAPI.Annoucement_Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<int?>("id_job")
                        .HasColumnType("int");

                    b.Property<int?>("id_naf_division")
                        .HasColumnType("int");

                    b.Property<int?>("id_student")
                        .HasColumnType("int");

                    b.Property<DateTime?>("publish_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("title")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("id_job");

                    b.HasIndex("id_naf_division");

                    b.HasIndex("id_student");

                    b.ToTable("Annoucement_Students");
                });

            modelBuilder.Entity("ShippeeAPI.Company", b =>
                {
                    b.Property<int>("siren")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cp")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("effective")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("id_naf")
                        .HasColumnType("int");

                    b.Property<string>("legal_form")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("payment")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("street")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("web_site")
                        .HasColumnType("varchar(255)");

                    b.HasKey("siren");

                    b.HasIndex("id_naf");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ShippeeAPI.Job", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("id_naf_division")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("id_naf_division");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ShippeeAPI.Naf_Division", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("id_naf")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("id_naf");

                    b.ToTable("Naf_Divisions");
                });

            modelBuilder.Entity("ShippeeAPI.Naf_Section", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.ToTable("Naf_Sections");
                });

            modelBuilder.Entity("ShippeeAPI.Qualification", b =>
                {
                    b.Property<int>("Annoucement_Companyid")
                        .HasColumnType("int");

                    b.Property<int>("Skillid")
                        .HasColumnType("int");

                    b.HasKey("Annoucement_Companyid", "Skillid");

                    b.HasIndex("Skillid");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("ShippeeAPI.Skill", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ShippeeAPI.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("birthday")
                        .HasColumnType("date");

                    b.Property<string>("city")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cv")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("fristname")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("id_company")
                        .HasColumnType("int");

                    b.Property<bool?>("is_online")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("password")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("picture")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("type_user")
                        .HasColumnType("int");

                    b.Property<string>("web_site")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("id_company");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkillUser", b =>
                {
                    b.Property<int>("skillid")
                        .HasColumnType("int");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("skillid", "userid");

                    b.HasIndex("userid");

                    b.ToTable("SkillUser");
                });

            modelBuilder.Entity("ShippeeAPI.Annoucement_Company", b =>
                {
                    b.HasOne("ShippeeAPI.Job", "Job")
                        .WithMany()
                        .HasForeignKey("id_job");

                    b.HasOne("ShippeeAPI.Naf_Division", "Naf_Division")
                        .WithMany()
                        .HasForeignKey("id_naf_division");

                    b.HasOne("ShippeeAPI.User", "User")
                        .WithMany()
                        .HasForeignKey("id_recruiter");

                    b.Navigation("Job");

                    b.Navigation("Naf_Division");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShippeeAPI.Annoucement_Student", b =>
                {
                    b.HasOne("ShippeeAPI.Job", "Job")
                        .WithMany()
                        .HasForeignKey("id_job");

                    b.HasOne("ShippeeAPI.Naf_Division", "Naf_Division")
                        .WithMany()
                        .HasForeignKey("id_naf_division");

                    b.HasOne("ShippeeAPI.User", "User")
                        .WithMany()
                        .HasForeignKey("id_student");

                    b.Navigation("Job");

                    b.Navigation("Naf_Division");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShippeeAPI.Company", b =>
                {
                    b.HasOne("ShippeeAPI.Naf_Section", "Naf_Section")
                        .WithMany()
                        .HasForeignKey("id_naf");

                    b.Navigation("Naf_Section");
                });

            modelBuilder.Entity("ShippeeAPI.Job", b =>
                {
                    b.HasOne("ShippeeAPI.Naf_Division", "Naf_Division")
                        .WithMany()
                        .HasForeignKey("id_naf_division");

                    b.Navigation("Naf_Division");
                });

            modelBuilder.Entity("ShippeeAPI.Naf_Division", b =>
                {
                    b.HasOne("ShippeeAPI.Naf_Section", "Naf_Section")
                        .WithMany()
                        .HasForeignKey("id_naf");

                    b.Navigation("Naf_Section");
                });

            modelBuilder.Entity("ShippeeAPI.Qualification", b =>
                {
                    b.HasOne("ShippeeAPI.Annoucement_Company", "Annoucement_Company")
                        .WithMany("Qualifications")
                        .HasForeignKey("Annoucement_Companyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippeeAPI.Skill", "Skill")
                        .WithMany("Qualifications")
                        .HasForeignKey("Skillid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annoucement_Company");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ShippeeAPI.User", b =>
                {
                    b.HasOne("ShippeeAPI.Company", "Company")
                        .WithMany()
                        .HasForeignKey("id_company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SkillUser", b =>
                {
                    b.HasOne("ShippeeAPI.Skill", null)
                        .WithMany()
                        .HasForeignKey("skillid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippeeAPI.User", null)
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShippeeAPI.Annoucement_Company", b =>
                {
                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("ShippeeAPI.Skill", b =>
                {
                    b.Navigation("Qualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
