// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShippeeAPI.Context;

#nullable disable

namespace ShippeeAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShippeeAPI.Company", b =>
                {
                    b.Property<int>("siren")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cp")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("effective")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("id_naf")
                        .HasColumnType("int");

                    b.Property<string>("legal_form")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("payment")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("street")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("web_site")
                        .HasColumnType("varchar(255)");

                    b.HasKey("siren");

                    b.HasIndex("id_naf");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ShippeeAPI.Job", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("id_naf_division")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("id_naf_division");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ShippeeAPI.Naf_Division", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("id_naf")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("id_naf");

                    b.ToTable("Naf_Divisions");
                });

            modelBuilder.Entity("ShippeeAPI.Naf_Section", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.ToTable("Naf_Sections");
                });

            modelBuilder.Entity("ShippeeAPI.Skill", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ShippeeAPI.Student_skill", b =>
                {
                    b.Property<int>("Userid")
                        .HasColumnType("int");

                    b.Property<int>("Skillid")
                        .HasColumnType("int");

                    b.HasKey("Userid", "Skillid");

                    b.HasIndex("Skillid");

                    b.ToTable("Student_skills");
                });

            modelBuilder.Entity("ShippeeAPI.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("birthday")
                        .HasColumnType("date");

                    b.Property<string>("city")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cv")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("fristname")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("id_company")
                        .HasColumnType("int");

                    b.Property<bool?>("is_online")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("password")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("picture")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("type_user")
                        .HasColumnType("int");

                    b.Property<string>("web_site")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("id_company");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShippeeAPI.Company", b =>
                {
                    b.HasOne("ShippeeAPI.Naf_Section", "Naf_Section")
                        .WithMany()
                        .HasForeignKey("id_naf");

                    b.Navigation("Naf_Section");
                });

            modelBuilder.Entity("ShippeeAPI.Job", b =>
                {
                    b.HasOne("ShippeeAPI.Naf_Division", "Naf_Division")
                        .WithMany()
                        .HasForeignKey("id_naf_division");

                    b.Navigation("Naf_Division");
                });

            modelBuilder.Entity("ShippeeAPI.Naf_Division", b =>
                {
                    b.HasOne("ShippeeAPI.Naf_Section", "Naf_Section")
                        .WithMany()
                        .HasForeignKey("id_naf");

                    b.Navigation("Naf_Section");
                });

            modelBuilder.Entity("ShippeeAPI.Student_skill", b =>
                {
                    b.HasOne("ShippeeAPI.Skill", "Skill")
                        .WithMany("Student_skills")
                        .HasForeignKey("Skillid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippeeAPI.User", "User")
                        .WithMany("Student_skills")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShippeeAPI.User", b =>
                {
                    b.HasOne("ShippeeAPI.Company", "Company")
                        .WithMany()
                        .HasForeignKey("id_company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ShippeeAPI.Skill", b =>
                {
                    b.Navigation("Student_skills");
                });

            modelBuilder.Entity("ShippeeAPI.User", b =>
                {
                    b.Navigation("Student_skills");
                });
#pragma warning restore 612, 618
        }
    }
}
