// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShippeeAPI.Context;

#nullable disable

namespace ShippeeAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShippeeAPI.Company", b =>
                {
                    b.Property<int>("siren")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cp")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("effective")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("id_naf")
                        .HasColumnType("int");

                    b.Property<string>("legal_form")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("payment")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("web_site")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("siren");

                    b.HasIndex("id_naf");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ShippeeAPI.Naf_Division", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("id_naf")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("id_naf");

                    b.ToTable("Naf_Divisions");
                });

            modelBuilder.Entity("ShippeeAPI.Naf_Section", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.ToTable("Naf_Sections");
                });

            modelBuilder.Entity("ShippeeAPI.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("birthday")
                        .HasColumnType("date");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cv")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("fristname")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("id_company")
                        .HasColumnType("int");

                    b.Property<bool>("is_online")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("picture")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("type_user")
                        .HasColumnType("int");

                    b.Property<string>("web_site")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("id_company");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShippeeAPI.Company", b =>
                {
                    b.HasOne("ShippeeAPI.Naf_Section", "Naf_Section")
                        .WithMany()
                        .HasForeignKey("id_naf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Naf_Section");
                });

            modelBuilder.Entity("ShippeeAPI.Naf_Division", b =>
                {
                    b.HasOne("ShippeeAPI.Naf_Section", "Naf_Section")
                        .WithMany()
                        .HasForeignKey("id_naf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Naf_Section");
                });

            modelBuilder.Entity("ShippeeAPI.User", b =>
                {
                    b.HasOne("ShippeeAPI.Company", "Company")
                        .WithMany()
                        .HasForeignKey("id_company")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
